const STYLES = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        backgroundColor: 'var(--background-primary)',
        color: 'var(--text-normal)',
        fontFamily: 'var(--font-interface)',
        overflow: 'hidden',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px 20px',
        background: 'var(--background-secondary)',
        borderBottom: '1px solid var(--background-modifier-border)',
    },
    title: {
        fontSize: '14px',
        fontWeight: '700',
        letterSpacing: '1px',
        color: 'var(--interactive-accent)',
        fontFamily: 'var(--font-monospace, monospace)'
    },
    content: {
        display: 'flex',
        flex: 1,
        overflow: 'hidden',
        padding: '20px',
        gap: '20px',
    },
    previewArea: {
        flex: 2,
        display: 'flex',
        flexDirection: 'column',
        gap: '15px',
        minWidth: 0,
    },
    asciiContainer: {
        flex: 1,
        background: 'var(--background-primary)',
        border: '1px solid var(--background-modifier-border)',
        borderRadius: '8px',
        overflow: 'auto',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        padding: '10px',
    },
    asciiDisplay: {
        fontFamily: 'var(--font-monospace, monospace)',
        fontSize: '10px',
        lineHeight: '1',
        margin: 0,
        whiteSpace: 'pre',
        color: 'var(--interactive-accent)',
        textAlign: 'center',
    },
    controlsArea: {
        flex: 1,
        background: 'var(--background-secondary)',
        borderRadius: '8px',
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        minWidth: '280px',
        border: '1px solid var(--background-modifier-border)',
        overflowY: 'auto',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '12px',
        fontWeight: '600',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
    },
    button: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        padding: '10px 16px',
        border: '1px solid var(--background-modifier-border)',
        borderRadius: '6px',
        backgroundColor: 'var(--background-modifier-hover)',
        color: 'var(--text-normal)',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    range: {
        width: '100%',
        accentColor: 'var(--interactive-accent)',
        cursor: 'pointer',
        background: 'var(--background-modifier-border)',
        borderRadius: '10px',
        height: '6px',
        appearance: 'none',
    },
    select: {
        background: 'var(--background-modifier-form-field)',
        color: 'var(--text-normal)',
        border: '1px solid var(--background-modifier-border)',
        padding: '10px',
        borderRadius: '6px',
        fontSize: '13px',
        outline: 'none',
        cursor: 'pointer',
    },
    exportSection: {
        marginTop: 'auto',
        borderTop: '1px solid var(--background-modifier-border)',
        paddingTop: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    }
};

return { STYLES };
